<?php

namespace PickingBundle\Repository;

/**
 * trv_manifiestosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trv_manifiestosRepository extends \Doctrine\ORM\EntityRepository
{
}
