<?php

namespace PickingBundle\Repository;

/**
 * trv_pickingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trv_pickingRepository extends \Doctrine\ORM\EntityRepository
{
}
