<?php

namespace PickingBundle\Repository;

/**
 * trv_emp_almRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trv_emp_almRepository extends \Doctrine\ORM\EntityRepository
{
}
